package rflib.common.sys;

extern class FSUtils {
	static var Fs : Dynamic;
	private static var S_IFBLK : Int;
	private static var S_IFCHR : Int;
	private static var S_IFDIR : Int;
	private static var S_IFIFO : Int;
	private static var S_IFLNK : Int;
	private static var S_IFMT : Int;
	private static var S_IFREG : Int;
	private static var S_IFSOCK : Int;
	private static var exists_cache : Map<String,Bool>;
	private static var lstatFields : Array<String>;
	private static var lstatTimes : Array<String>;
	static function cachedExists(path : String) : Bool;
	static function copyDirectory(src_path : String, dest_path : String) : Void;
	static function copyFile(srcPath : String, dstPath : String, bufsize : Null<Int> = 0) : Void;
	static function createDir(path : String) : String;
	static function createDirectory(dir : String) : Void;
	static function createUniquePrefixDir(prefix : String, enter : Null<Bool> = false) : String;
	@:pure(inferredPure) static function delete(path : String) : Void;
	static function deleteDirectory(path : rflib.common.Str, self : Null<Bool> = false) : Void;
	static function dirContext(path : String, cb : () -> Void) : Void;
	static function getFilenames(paths : Array<String>) : Array<String>;
	static function getTempDir() : String;
	static function getUniqueFilePath(path : String) : String;
	static function ifModifiedAdjustDestMTime(srcPath : rflib.common.Str, destPath : rflib.common.Str, cb : rflib.common.Str -> rflib.common.Str -> Bool, force : Null<Bool> = false) : Bool;
	static function joinPath(path : Array<String>, ?name : String) : String;
	static function joinSlashes(parts : Array<String>) : String;
	static function lstat(path : String) : FileStatPlus;
	static function makeHardlink(from : String, to : String) : Void;
	static function makeSymlink(from : String, to : String) : Void;
	private static function modeSetType(st : FileStat64) : Void;
	static function parsePath(path : String) : {file : String, ext : String, dir : String};
	static function pathFilename(p : String) : String;
	static function readLink(path : String) : String;
	static function relativePath(path : String, relativeTo : String) : String;
	static function remSlashes(path : String) : String;
	static function rename(src : String, dest : String) : String;
	static function resolveSymlink(path : String) : String;
	static function safeDeleteDirectory(path : String) : Void;
	static function safeDeleteFile(path : String) : Void;
	static function safeFileCopy(src : String, dest : String, do_unique : Null<Bool> = false) : String;
	static function safeIsDirectory(path : String) : Bool;
	static function safeReadDirectory(path : String) : Array<String>;
	static function safeRename(src : String, dest : String, do_unique : Null<Bool> = false) : String;
	static function safeStat(path : String) : sys.FileStat;
	static function trailSlash(path : String) : String;
	static function traverseDirectory(base_path : String, cb : Array<String> -> String -> FileStatPlus -> TraverseResult, leave_dir_cb : Null<Array<String> -> String -> Void> = null, on_list_cb : Null<Array<String> -> Array<String> -> Array<FileStatPlus> -> Void> = null, max_depth : Null<Int> = 0) : TraverseResult;
}
